// Flat ESLint config for the Oculis Auribus TS monorepo (Next.js web app + worker +
// shared packages). Pragmatic by design: errors only for real bugs (rules-of-hooks,
// unused vars), warnings for stylistic/uncertain things, and no type-aware linting so
// it stays fast and never needs per-package tsconfig wiring. Run with `npm run lint`.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

export default tseslint.config(
  // Never lint build output, deps, or generated/data artifacts.
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.tsbuildinfo",
      ".data/**",
      ".pgdata/**",
      "**/drizzle/**",
      "**/next-env.d.ts", // generated by Next.js
      // Claude Code Workflow scripts: they run in a sandboxed runtime that
      // injects globals (agent, phase, parallel, log, args) ESLint can't know.
      "scripts/*.workflow.js",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Shared rules for all TS/JS source.
  {
    files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // Real bugs → error.
      "no-unused-vars": "off", // superseded by the TS-aware rule below
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", ignoreRestSiblings: true, caughtErrors: "none" },
      ],
      // Stylistic / opinion → warn so CI lint stays green while still flagging.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "prefer-const": "warn",
      "no-console": "off",
      // These ship as errors in js.configs.recommended but are stylistic, not bugs —
      // soften to warn so they don't block CI on pre-existing code.
      "no-useless-escape": "warn",
      "no-empty": "warn",
    },
  },

  // React Hooks correctness for the Next.js web app — rules-of-hooks is a real bug.
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    languageOptions: {
      globals: { ...globals.browser },
    },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // Test files: relax a couple of rules that fight with test ergonomics.
  {
    files: ["**/*.test.{ts,tsx}", "**/test/**/*.{ts,tsx}", "**/__tests__/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
